name: Daily Digest

on:
  schedule:
    - cron: "30 13 * * *" # Runs daily at 7:00 PM IST (UTC+5:30)
  workflow_dispatch: # Allows manual runs for testing

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Send Daily Digest
        uses: fjogeleit/http-request-action@v1
        with:
          url: "${{ secrets.VERCEL_URL }}/api/webhook/github/daily-digest"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json", "Authorization": "Bearer ${{ secrets.GITHUB_WEBHOOK_SECRET }}"}'
