name: Scheduled Email Reminder

on:
  schedule:
    - cron: "25 14 * * *" # Runs daily at 19:55 PM IST (UTC+5:30)
  workflow_dispatch: # Allows manual runs for testing

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Send Scheduled Email Reminder
        uses: fjogeleit/http-request-action@v1
        with:
          url: "vercel.url/api/webhook/github/scheduled"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          data: '{"auth": "${{ secrets.AUTH_SECRET_TOKEN }}"}'
